name: clang-format
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: '.'
        extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx,i,ixx,ipp,i++'
        clangFormatVersion: 14
        inplace: False
